// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZm_AcWCBbwPCyZ56HPHIf5zPrXhiUafo',
    appId: '1:1039601930282:web:1d27ec12d0e5ad7793f353',
    messagingSenderId: '1039601930282',
    projectId: 'wallstone-2b323',
    authDomain: 'wallstone-2b323.firebaseapp.com',
    databaseURL: 'https://wallstone-2b323.firebaseio.com',
    storageBucket: 'wallstone-2b323.appspot.com',
    measurementId: 'G-Y3L8C14VY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF9wqgjf6OLCRdV0oizzKrYHKqYk7_0O8',
    appId: '1:1039601930282:android:92f3e37dab9751e2',
    messagingSenderId: '1039601930282',
    projectId: 'wallstone-2b323',
    databaseURL: 'https://wallstone-2b323.firebaseio.com',
    storageBucket: 'wallstone-2b323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqJt-BKoWkQir3D_qwJt97w5t-Zvriew0',
    appId: '1:1039601930282:ios:6fdfc2610d25edec93f353',
    messagingSenderId: '1039601930282',
    projectId: 'wallstone-2b323',
    databaseURL: 'https://wallstone-2b323.firebaseio.com',
    storageBucket: 'wallstone-2b323.appspot.com',
    androidClientId: '1039601930282-pdjv43nno5cdjepo4ilk6js3t9qssdsp.apps.googleusercontent.com',
    iosClientId: '1039601930282-84viptbk19v53b66fuao85lrq1d0hrsg.apps.googleusercontent.com',
    iosBundleId: 'com.mecho.wallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqJt-BKoWkQir3D_qwJt97w5t-Zvriew0',
    appId: '1:1039601930282:ios:6fdfc2610d25edec93f353',
    messagingSenderId: '1039601930282',
    projectId: 'wallstone-2b323',
    databaseURL: 'https://wallstone-2b323.firebaseio.com',
    storageBucket: 'wallstone-2b323.appspot.com',
    androidClientId: '1039601930282-pdjv43nno5cdjepo4ilk6js3t9qssdsp.apps.googleusercontent.com',
    iosClientId: '1039601930282-84viptbk19v53b66fuao85lrq1d0hrsg.apps.googleusercontent.com',
    iosBundleId: 'com.mecho.wallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZm_AcWCBbwPCyZ56HPHIf5zPrXhiUafo',
    appId: '1:1039601930282:web:d65ff6bbac822cb993f353',
    messagingSenderId: '1039601930282',
    projectId: 'wallstone-2b323',
    authDomain: 'wallstone-2b323.firebaseapp.com',
    databaseURL: 'https://wallstone-2b323.firebaseio.com',
    storageBucket: 'wallstone-2b323.appspot.com',
    measurementId: 'G-622D0DZT2E',
  );
}
