/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData twitter = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData linkedin =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData email = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData format_indent_increase =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData list_nested =
      const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData format_align_left =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData facebook_rect =
      const IconData(0xf301, fontFamily: _kFontFam);
  static const IconData instagram =
      const IconData(0xf31e, fontFamily: _kFontFam);
}
